server:
  http_listen_port: 9080
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Add the Docker container log file as the target to read from
      - source_labels: ['__meta_docker_container_log_path']
        target_label: '__path__'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_hostname']
        target_label: 'hostname'
      - source_labels: ['__meta_docker_container_label_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_env']
        target_label: 'env'
      # Map container_name to job label and remove leading "/" from container name
      - source_labels: ['__meta_docker_container_name']
        regex: '^/(.*)'
        replacement: '${1}'
        target_label: 'job'
