apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: P8E80F9AEF21F6940
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true

  - name: PostgreSQL
    type: postgres
    uid: PCC52D03280B7034C
    access: proxy
    jsonData:
      database: infinite
      host: db
      port: 5432
      sslmode: disable
      user: ieuser
    secureJsonData:
      password: ${PG_PASSWORD}
    isDefault: false
    editable: true
